# CI Pipeline for PocketForager

name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:                 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Giving permission for gradlew
        run: chmod +x ./gradlew

      - name: Build without tests
        run: ./gradlew assembleDebug --no-daemon

      - name: Tests and coverage
        run: ./gradlew testDebugUnitTest jacocoTestReportDebug jacocoCoverageCheck --no-daemon

      - name: JaCoCo HTML
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: app/build/reports/jacoco/jacocoUnitTestReport/html
          retention-days: 7



